// Generated by https://quicktype.io

import { TransactionStatus } from 'src/transactions/enums/transaction-status';

export interface IKey2PayNotifyResponse {
  uid: string;
  status: TransactionStatus;
  message: string;
  creationDate: string;
  notificationDate: string;
  amount: number;
  description: string;
  currency: string;
  language: string;
  orderId: string;
  customer: Customer;
}

export interface Customer {
  address: string;
  city: string;
  country: string;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  postcode: string;
  personalId: string;
  ip: string;
}
