// Generated by https://quicktype.io

export interface IKey2PayPaymentMethods {
  uid: string;
  name: Name;
  country: string;
  channel: Channel;
  imageUrl: string;
  currencies: string[];
}

export enum Channel {
  Cash = 'CASH',
  CreditCard = 'CREDIT_CARD',
  Online = 'ONLINE',
}

export enum Name {
  BankTransfer = 'Bank Transfer',
  Boleto = 'Boleto',
  CreditCard = 'Credit Card',
}
