// Generated by https://quicktype.io

export interface IKey2PayPayingResponse {
  uid: string;
  message: string;
  createdAt: string;
  description: string;
  currency: string;
  amount: number;
  language: string;
  orderId: string;
  customer: { [key: string]: null | string };
  form: Form;
  paymentFormUrl: string;
}

export interface Form {
  action: string;
  method: string;
}
