// Generated by https://quicktype.io

export interface IKey2payPayBody {
  currency: string;
  amount: number;
  language?: string;
  orderId: string;
  description: string;
  notificationUrl: string;
  customer: Customer;
}

export interface Customer {
  firstName: string;
  lastname: string;
  personalid: string;
  email: string;
  country: string;
  city: string;
  postcode: string;
  address: string;
  phone: string;
  ip: string;
}
